flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- GLURaw-1.5.0.2
- GLUT-2.7.0.3
- ObjectName-1.1.0.0
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.5.0
- gloss-1.9.4.1
- gloss-rendering-1.9.3.1
- bindings-GLFW-3.1.1.4
- GLFW-b-1.4.7.3
- gloss-algorithms-1.9.4.1
- gloss-raster-1.9.4.1
- gloss-examples-1.9.4.1
resolver: lts-3.17
